apiVersion: backstage.io/v1alpha1
kind: Component
spec:
  system: "system:default/examples"
  type:  "service"
  lifecycle: "experimental"
  owner: "group:default/guests"
metadata:
  name: "go-skyapp01"
  description: "Golang App"
  annotations:
    github.com/project-slug: cwiklik/go-skyapp01
    backstage.io/techdocs-ref: dir:.
    argocd/app-name: go-skyapp01-dev
    backstage.io/kubernetes-id: "go-skyapp01"
    sonarqube.org/project-key: "go-skyapp01"
    grafana/tag-selector: "Kubernetes"
    prometheus.io/rule: container_cpu_usage_seconds_total{namespace="go-skyapp01"}
    prometheus.io/alert: all
  tags:
    - golang
    - "system:default/examples"
    - "service"
    - "experimental"
  links:
    - url: https://go-skyapp01.
      title: Website
      icon: Website
    - url: https://grafana.diegoluisi.eti.br/
      title: Dashboard
      icon: dashboard
    - url: https://alerts.diegoluisi.eti.br/
      title: Alerts
      icon: alert
    - url: https://argocd.diegoluisi.eti.br/applications/go-skyapp01-dev?resource=
      title: ArgoCD
      icon: cloud
    - url: https://grafana.diegoluisi.eti.br/d/k8s_views_ns/kubernetes-views-namespaces?orgId=1&refresh=30s&var-datasource=Prometheus&var-namespace=go-skyapp01&var-resolution=30s
      title: Logs
      icon: cloud
    - url: https://kiali.diegoluisi.eti.br/kiali/console/graph/namespaces/?traffic=grpc%2CgrpcRequest%2Chttp%2ChttpRequest%2Ctcp%2CtcpSent&graphType=versionedApp&namespaces=go-skyapp01&duration=120&refresh=60000&idleNodes=true&layout=kiali-breadthfirst&namespaceLayout=kiali-dagre
      title: Kiali
      icon: cloud
