site_name: 'go-skyapp01'
site_description: 'Main documentation for Backstage features and platform APIs'
repo_url: https://github.com/cwiklik/go-skyapp01
edit_uri: edit/main/docs

plugins:
  - techdocs-core

nav:
  - Getting Started:
      - Getting Started: 'docs/index.md'
